<?php

namespace Database\Seeders;

use App\Models\Form;
use App\Models\FormField;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class RecognitionNominationSeeder extends Seeder
{
    public function run(): void
    {
        $form = Form::updateOrCreate(
            ['slug' => 'nomination-form'],
            [
                'name' => 'Award Nomination',
                'description' => 'Official nomination form for World Grexpo Business Excellence Awards.',
                'status' => 'published',
                'submit_button_text' => 'Submit Nomination',
                'thank_you_message' => 'Thank you for your nomination. We will review it and get back to you shortly.',
            ]
        );

        $fields = [
            [
                'field_identifier' => 'nomination_type',
                'label' => 'Nomination Type',
                'type' => 'dropdown',
                'is_required' => true,
                'options' => [
                    ["label" => "World Grexpo National Golden Business Excellence Award", "price" => 500000, "tax" => 18],
                    ["label" => "Business Leader of the Year", "price" => 600000, "tax" => 18],
                    ["label" => "World Grexpo National Platinum Business Excellence Award", "price" => 50000, "tax" => 18],
                    ["label" => "World Grexpo National Diamond Business Excellence Award", "price" => 750000, "tax" => 18],
                    ["label" => "World Grexpo Make in India Initiative Award", "price" => 1000000, "tax" => 18],
                    ["label" => "World Grexpo Lifetime Achievement Award", "price" => 200000, "tax" => 18],
                    ["label" => "BEST CEO AWARD", "price" => 50000, "tax" => 18],
                    ["label" => "BEST CFO AWARD", "price" => 50000, "tax" => 18],
                    ["label" => "BEST CMO AWARD", "price" => 50000, "tax" => 18],
                    ["label" => "BEST CIO AWARD", "price" => 50000, "tax" => 18],
                    ["label" => "World Grexpo Bharat Ratan Award", "price" => 300000, "tax" => 18],
                    ["label" => "Best Sustainable company of the year", "price" => 150000, "tax" => 18],
                    ["label" => "Best Machine Tool Manufacturers of the year", "price" => 50000, "tax" => 18],
                    ["label" => "Education Excellence Award", "price" => 25000, "tax" => 18],
                    ["label" => "Best Founder of IT company of the year", "price" => 150000, "tax" => 18],
                    ["label" => "Best Manufacturing Company Award", "price" => 100000, "tax" => 18],
                    ["label" => "Best Sustainable Company of the Year", "price" => 150000, "tax" => 18],
                    ["label" => "Bharat Ratan Award", "price" => 300000, "tax" => 18],
                    ["label" => "High Industry Award – National Level", "price" => 200000, "tax" => 18],
                    ["label" => "Elite Leadership Award", "price" => 250000, "tax" => 18],
                    ["label" => "Premium & Grand Award", "price" => 400000, "tax" => 18],
                    ["label" => "Ultimate & Exclusive Award", "price" => 500000, "tax" => 18],
                    ["label" => "Rashtriya Gaurav Excellence Award", "price" => 400000, "tax" => 18],
                    ["label" => "Global Bharat Leadership Award", "price" => 500000, "tax" => 18],
                    ["label" => "Vishwa Ratna Award", "price" => 600000, "tax" => 18],
                    ["label" => "World Leadership Excellence Award", "price" => 750000, "tax" => 18],
                    ["label" => "Global Legend Award", "price" => 1000000, "tax" => 18]
                ],
                'order' => 1,
            ],
            [
                'field_identifier' => 'category',
                'label' => 'Category',
                'type' => 'dropdown',
                'is_required' => true,
                'options' => [
                    ['label' => '1. Agriculture'],
                    ['label' => '2. Artificial Intelligence (AI)'],
                    ['label' => '3. Auto Retail'],
                    ['label' => '4. Aerospace'],
                    ['label' => '5. Automobile & Lubrication'],
                    ['label' => '6. Banking, Financial Services & Insurance (BFSI)'],
                    ['label' => '7. Beauty Products, Services & Solutions'],
                    ['label' => '8. Biogas'],
                    ['label' => '9. Biotechnology'],
                    ['label' => '10. Blockchain'],
                    ['label' => '11. Chief Executive Officers (CEO)'],
                    ['label' => '12. Corporate Social Responsibility (CSR)'],
                    ['label' => '13. Cyber Security'],
                    ['label' => '14. COVID-19 Social Work'],
                    ['label' => '15. Customer Service'],
                    ['label' => '16. Construction'],
                    ['label' => '17. Decarbonization'],
                    ['label' => '18. Drones'],
                    ['label' => '19. E-Waste'],
                    ['label' => '20. E-Commerce'],
                    ['label' => '21. EdTech'],
                    ['label' => '22. Education'],
                    ['label' => '23. Electric Vehicles (EVs)'],
                    ['label' => '24. Engineering'],
                    ['label' => '25. Entertainment'],
                    ['label' => '26. Entrepreneur'],
                    ['label' => '27. Excellence in PSU'],
                    ['label' => '28. Export & Import'],
                    ['label' => '29. Flexible Packaging'],
                    ['label' => '30. Food & Grocery'],
                    ['label' => '31. Green Future'],
                    ['label' => '32. Healthcare'],
                    ['label' => '33. Hotel Industry'],
                    ['label' => '34. Housing & Properties'],
                    ['label' => '35. Human Resources (HR)'],
                    ['label' => '36. Information Technology'],
                    ['label' => '37. Infrastructure'],
                    ['label' => '38. Innovation'],
                    ['label' => '39. Jewellery'],
                    ['label' => '40. Logistics & Supply Chain'],
                    ['label' => '41. Manufacturing'],
                    ['label' => '42. Non-Ferrous Metals & Scrap Recycling'],
                    ['label' => '43. Oil & Gas'],
                    ['label' => '44. Other Categories (Open Category)'],
                    ['label' => '45. Packaging'],
                    ['label' => '46. Plastic Recycling & Waste Management'],
                    ['label' => '47. Pharma'],
                    ['label' => '48. Print & Publishing'],
                    ['label' => '49. Real Estate'],
                    ['label' => '50. Renewable Energy'],
                    ['label' => '51. Retail'],
                    ['label' => '52. Robotics'],
                    ['label' => '53. Retail'],
                    ['label' => '54. Renewable Energy'],
                    ['label' => '55. Real Estate'],
                    ['label' => '56. Research & Development (R&D)'],
                    ['label' => '57. Robotics & Automation'],
                    ['label' => '58. Steel & Metals'],
                    ['label' => '59. Startups'],
                    ['label' => '60. Telecom'],
                    ['label' => '61. Textiles & Apparel'],
                    ['label' => '62. Travel & Tourism'],
                    ['label' => '63. Warehousing & Logistics'],
                    ['label' => '64. Water Conservation'],
                    ['label' => '65. Waste Management'],
                    ['label' => '66. Packaging Industry'],
                    ['label' => '67. Printing & Converting'],
                    ['label' => '68. Specialty Chemicals'],
                    ['label' => '69. Pharmaceuticals'],
                    ['label' => '70. Healthcare & Hospitals'],
                    ['label' => '71. Food Processing & FMCG'],
                    ['label' => '72. Hospitality (Hotels & Resorts)'],
                    ['label' => '73. Media & Advertising'],
                    ['label' => '74. IT & Software'],
                    ['label' => '75. Legal & Compliance'],
                    ['label' => '76. Human Resources (HR)'],
                    ['label' => '77. Import & Export'],
                    ['label' => '78. NGOs & Social Impact'],
                    ['label' => '79. Award Benefits (Positioning Categories)'],
                    ['label' => '80. Recycling Sector – Exclusivity Award'],
                    ['label' => '81. Waste Management – Exclusivity Award'],
                    ['label' => '82. Solar Energy – Exclusivity Award'],
                    ['label' => '83. Automobile Industry – Exclusivity Award'],
                    ['label' => '84. Electric Mobility – Exclusivity Award'],
                    ['label' => '85. Battery Recycling – Exclusivity Award'],
                ],
                'order' => 2,
            ],
            [
                'field_identifier' => 'sub_category',
                'label' => 'Sub Category',
                'type' => 'dropdown',
                'is_required' => true,
                'depends_on' => 'category',
                'depends_on_value' => '__MAPPED__',
                'options' => [
                    '1. Agriculture' => [
                        ['label' => 'Agri Innovation Award'],
                        ['label' => 'Smart Farming Technology'],
                        ['label' => 'Organic Farming Excellence'],
                        ['label' => 'Agri Export Excellence'],
                        ['label' => 'Agri Startup of the Year'],
                    ],
                    '2. Artificial Intelligence (AI)' => [
                        ['label' => 'AI Innovation of the Year'],
                        ['label' => 'AI for Sustainability'],
                        ['label' => 'AI Startup Excellence'],
                        ['label' => 'Enterprise AI Implementation'],
                        ['label' => 'AI in Manufacturing / Healthcare'],
                    ],
                    '3. Auto Retail' => [
                        ['label' => 'Best Auto Dealership'],
                        ['label' => 'Customer Experience Excellence'],
                        ['label' => 'Digital Auto Retail Innovation'],
                        ['label' => 'Multi-Brand Retail Excellence'],
                    ],
                    '4. Aerospace' => [
                        ['label' => 'Aerospace Innovation'],
                        ['label' => 'Defence Manufacturing Contribution'],
                        ['label' => 'Component Manufacturing Excellence'],
                        ['label' => 'R&D Excellence in Aerospace'],
                    ],
                    '5. Automobile & Lubrication' => [
                        ['label' => 'EV Innovation Leader'],
                        ['label' => 'Auto Component Excellence'],
                        ['label' => 'Lubricant Innovation Award'],
                        ['label' => 'Sustainable Mobility Leader'],
                        ['label' => 'Manufacturing Excellence'],
                    ],
                    '6. Banking, Financial Services & Insurance (BFSI)' => [
                        ['label' => 'Digital Banking Innovation'],
                        ['label' => 'Fintech Excellence'],
                        ['label' => 'Risk Management Leader'],
                        ['label' => 'Customer Experience in BFSI'],
                        ['label' => 'ESG & Green Finance'],
                    ],
                    '7. Beauty Products, Services & Solutions' => [
                        ['label' => 'Beauty Brand of the Year'],
                        ['label' => 'Organic / Natural Product Innovation'],
                        ['label' => 'Salon Chain Excellence'],
                        ['label' => 'D2C Beauty Brand'],
                        ['label' => 'Sustainable Beauty Leader'],
                    ],
                    '8. Biogas' => [
                        ['label' => 'Waste to Energy Innovation'],
                        ['label' => 'Biogas Plant Excellence'],
                        ['label' => 'Rural Energy Impact'],
                        ['label' => 'Clean Energy Startup'],
                    ],
                    '9. Biotechnology' => [
                        ['label' => 'Biotech Innovation'],
                        ['label' => 'Healthcare Biotechnology'],
                        ['label' => 'Agri Biotech Excellence'],
                        ['label' => 'Research & Development Excellence'],
                    ],
                    '10. Blockchain' => [
                        ['label' => 'Blockchain Startup'],
                        ['label' => 'Blockchain in Supply Chain'],
                        ['label' => 'Fintech Blockchain Innovation'],
                        ['label' => 'Web3 Innovation Award'],
                    ],
                    '11. Chief Executive Officers (CEO)' => [
                        ['label' => 'CEO of the Year (Large / MSME)'],
                        ['label' => 'Young CEO (<40)'],
                        ['label' => 'Transformational Leader'],
                        ['label' => 'Sustainability CEO'],
                        ['label' => 'Startup CEO'],
                    ],
                    '12. Corporate Social Responsibility (CSR)' => [
                        ['label' => 'CSR Impact Award'],
                        ['label' => 'Rural Development Initiative'],
                        ['label' => 'Education Impact CSR'],
                        ['label' => 'Healthcare CSR'],
                        ['label' => 'Environmental Sustainability CSR'],
                    ],
                    '13. Cyber Security' => [
                        ['label' => 'Cybersecurity Innovation'],
                        ['label' => 'Data Protection Excellence'],
                        ['label' => 'Enterprise Security Leader'],
                        ['label' => 'Startup in Cybersecurity'],
                    ],
                    '14. COVID-19 Social Work' => [
                        ['label' => 'Pandemic Hero Award'],
                        ['label' => 'Healthcare Support Initiative'],
                        ['label' => 'Community Relief Leadership'],
                        ['label' => 'NGO Impact Award'],
                    ],
                    '15. Customer Service' => [
                        ['label' => 'Customer Experience Excellence'],
                        ['label' => 'Digital Customer Engagement'],
                        ['label' => 'Service Innovation Award'],
                        ['label' => 'Omni-channel Service Leader'],
                    ],
                    '16. Construction' => [
                        ['label' => 'Infrastructure Project Excellence'],
                        ['label' => 'Sustainable Construction'],
                        ['label' => 'Smart City Contribution'],
                        ['label' => 'Real Estate Innovation'],
                    ],
                    '17. Decarbonization' => [
                        ['label' => 'Net Zero Leadership'],
                        ['label' => 'Carbon Reduction Innovation'],
                        ['label' => 'Clean Energy Adoption'],
                        ['label' => 'Green Manufacturing'],
                    ],
                    '18. Drones' => [
                        ['label' => 'Drone Innovation Award'],
                        ['label' => 'Drone in Agriculture'],
                        ['label' => 'Defence Drone Technology'],
                        ['label' => 'Commercial Drone Applications'],
                    ],
                    '19. E-Waste' => [
                        ['label' => 'Recycling Excellence'],
                        ['label' => 'Circular Economy Leader'],
                        ['label' => 'E-Waste Collection Innovation'],
                        ['label' => 'Sustainability Impact Award'],
                    ],
                    '20. E-Commerce' => [
                        ['label' => 'E-Commerce Brand of the Year'],
                        ['label' => 'D2C Excellence'],
                        ['label' => 'Logistics & Fulfillment Innovation'],
                        ['label' => 'Customer Experience in E-Commerce'],
                    ],
                    '21. EdTech' => [
                        ['label' => 'EdTech Innovation'],
                        ['label' => 'Online Learning Platform'],
                        ['label' => 'Skill Development Impact'],
                        ['label' => 'AI in Education'],
                    ],
                    '22. Education' => [
                        ['label' => 'Institution of the Year'],
                        ['label' => 'Skill Development Excellence'],
                        ['label' => 'Industry-Academia Collaboration'],
                        ['label' => 'Rural Education Impact'],
                    ],
                    '23. Electric Vehicles (EVs)' => [
                        ['label' => 'EV Manufacturer of the Year'],
                        ['label' => 'EV Startup'],
                        ['label' => 'Battery Innovation'],
                        ['label' => 'Charging Infrastructure Leader'],
                        ['label' => 'EV Component Manufacturer'],
                    ],
                    '24. Engineering' => [
                        ['label' => 'Engineering Excellence'],
                        ['label' => 'Precision Manufacturing'],
                        ['label' => 'Industrial Innovation'],
                        ['label' => 'Export Excellence'],
                    ],
                    '25. Entertainment' => [
                        ['label' => 'Media Innovation'],
                        ['label' => 'Digital Content Creator'],
                        ['label' => 'Production Excellence'],
                        ['label' => 'OTT Platform Excellence'],
                    ],
                    '26. Entrepreneur' => [
                        ['label' => 'Entrepreneur of the Year'],
                        ['label' => 'Young Entrepreneur (<40)'],
                        ['label' => 'Women Entrepreneur'],
                        ['label' => 'Social Entrepreneur'],
                        ['label' => 'Startup Founder Excellence'],
                        ['label' => 'Serial Entrepreneur'],
                    ],
                    '27. Excellence in PSU' => [
                        ['label' => 'PSU of the Year'],
                        ['label' => 'Innovation in PSU'],
                        ['label' => 'Sustainability in PSU'],
                        ['label' => 'Digital Transformation – PSU'],
                        ['label' => 'Operational Excellence'],
                    ],
                    '28. Export & Import' => [
                        ['label' => 'Export Excellence Award'],
                        ['label' => 'Import Substitution Leader'],
                        ['label' => 'Global Trade Leader'],
                        ['label' => 'International Expansion Award'],
                        ['label' => 'Supply Chain Excellence'],
                    ],
                    '29. Flexible Packaging' => [
                        ['label' => 'Flexible Packaging Excellence'],
                        ['label' => 'Sustainable Flexible Packaging'],
                        ['label' => 'High Barrier Innovation'],
                        ['label' => 'Printing & Converting Excellence'],
                        ['label' => 'FMCG Packaging Leader'],
                    ],
                    '30. Food & Grocery' => [
                        ['label' => 'FMCG Brand of the Year'],
                        ['label' => 'Food Innovation Award'],
                        ['label' => 'Packaged Food Excellence'],
                        ['label' => 'Retail Grocery Chain'],
                        ['label' => 'Export Excellence – Food'],
                    ],
                    '31. Green Future' => [
                        ['label' => 'Climate Action Leader'],
                        ['label' => 'Net Zero Initiative'],
                        ['label' => 'Renewable Adoption Excellence'],
                        ['label' => 'Green Innovation Award'],
                        ['label' => 'ESG Leadership'],
                    ],
                    '32. Healthcare' => [
                        ['label' => 'Healthcare Provider of the Year'],
                        ['label' => 'Medical Innovation Award'],
                        ['label' => 'Hospital Excellence'],
                        ['label' => 'Digital Health Innovation'],
                        ['label' => 'Rural Healthcare Impact'],
                    ],
                    '33. Hotel Industry' => [
                        ['label' => 'Hotel of the Year'],
                        ['label' => 'Luxury Hospitality Award'],
                        ['label' => 'Boutique Hotel Excellence'],
                        ['label' => 'Guest Experience Leader'],
                        ['label' => 'Sustainable Hospitality'],
                    ],
                    '34. Housing & Properties' => [
                        ['label' => 'Affordable Housing Excellence'],
                        ['label' => 'Smart Housing Project'],
                        ['label' => 'Sustainable Housing'],
                        ['label' => 'Residential Project of the Year'],
                        ['label' => 'Developer Excellence'],
                    ],
                    '35. Human Resources (HR)' => [
                        ['label' => 'HR Excellence Award'],
                        ['label' => 'Talent Management Leader'],
                        ['label' => 'Employee Engagement Excellence'],
                        ['label' => 'Diversity & Inclusion'],
                        ['label' => 'HR Tech Innovation'],
                    ],
                    '36. Information Technology' => [
                        ['label' => 'IT Company of the Year'],
                        ['label' => 'Software Innovation'],
                        ['label' => 'SaaS Excellence'],
                        ['label' => 'Cloud Transformation'],
                        ['label' => 'AI & Data Leadership'],
                    ],
                    '37. Infrastructure' => [
                        ['label' => 'Infrastructure Project of the Year'],
                        ['label' => 'Smart City Development'],
                        ['label' => 'Sustainable Infrastructure'],
                        ['label' => 'EPC Excellence'],
                        ['label' => 'Urban Development Leadership'],
                    ],
                    '38. Innovation' => [
                        ['label' => 'Innovation of the Year'],
                        ['label' => 'Disruptive Technology Award'],
                        ['label' => 'Product Innovation'],
                        ['label' => 'Process Innovation'],
                        ['label' => 'R&D Excellence'],
                    ],
                    '39. Jewellery' => [
                        ['label' => 'Jewellery Brand of the Year'],
                        ['label' => 'Design Innovation'],
                        ['label' => 'Luxury Jewellery Excellence'],
                        ['label' => 'Export Excellence – Jewellery'],
                        ['label' => 'Retail Chain Excellence'],
                    ],
                    '40. Logistics & Supply Chain' => [
                        ['label' => 'Supply Chain Excellence'],
                        ['label' => 'Logistics Innovation'],
                        ['label' => 'Cold Chain Excellence'],
                        ['label' => 'E-Commerce Logistics Leader'],
                        ['label' => 'Green Logistics'],
                    ],
                    '41. Manufacturing' => [
                        ['label' => 'Manufacturing Excellence'],
                        ['label' => 'Smart Factory (Industry 4.0)'],
                        ['label' => 'Export Excellence'],
                        ['label' => 'Quality Leadership'],
                        ['label' => 'Lean Manufacturing'],
                    ],
                    '42. Non-Ferrous Metals & Scrap Recycling' => [
                        ['label' => 'Metal Recycling Excellence'],
                        ['label' => 'Circular Economy Leader'],
                        ['label' => 'Scrap Processing Innovation'],
                        ['label' => 'Export Excellence'],
                        ['label' => 'Sustainable Metal Production'],
                    ],
                    '43. Oil & Gas' => [
                        ['label' => 'Energy Company of the Year'],
                        ['label' => 'Exploration Excellence'],
                        ['label' => 'Refining & Processing Innovation'],
                        ['label' => 'Safety Excellence'],
                        ['label' => 'Sustainability in Oil & Gas'],
                    ],
                    '44. Other Categories (Open Category)' => [
                        ['label' => 'Special Jury Award'],
                        ['label' => 'Emerging Sector Award'],
                        ['label' => 'Innovation Beyond Boundaries'],
                        ['label' => 'Custom Industry Category'],
                        ['label' => 'Unique Business Model Award'],
                    ],
                    '45. Packaging' => [
                        ['label' => 'Packaging Innovation Award'],
                        ['label' => 'Sustainable Packaging Leader'],
                        ['label' => 'Rigid Packaging Excellence'],
                        ['label' => 'Flexible Packaging Excellence'],
                        ['label' => 'Design & Branding'],
                    ],
                    '46. Plastic Recycling & Waste Management' => [
                        ['label' => 'Plastic Recycling Excellence'],
                        ['label' => 'Waste Management Innovation'],
                        ['label' => 'Circular Economy Leader'],
                        ['label' => 'Waste-to-Energy'],
                        ['label' => 'ESG Impact Award'],
                    ],
                    '47. Pharma' => [
                        ['label' => 'Pharma Company of the Year'],
                        ['label' => 'API Manufacturing Excellence'],
                        ['label' => 'R&D Innovation'],
                        ['label' => 'Export Excellence'],
                        ['label' => 'Healthcare Impact'],
                    ],
                    '48. Print & Publishing' => [
                        ['label' => 'Printing Excellence'],
                        ['label' => 'Digital Printing Innovation'],
                        ['label' => 'Publishing House of the Year'],
                        ['label' => 'Packaging Printing'],
                        ['label' => 'Sustainable Printing'],
                    ],
                    '49. Real Estate' => [
                        ['label' => 'Developer of the Year'],
                        ['label' => 'Commercial Project Excellence'],
                        ['label' => 'Residential Project Excellence'],
                        ['label' => 'Smart Infrastructure'],
                        ['label' => 'Sustainable Real Estate'],
                    ],
                    '50. Renewable Energy' => [
                        ['label' => 'Solar Energy Excellence'],
                        ['label' => 'Wind Energy Innovation'],
                        ['label' => 'Energy Storage Solutions'],
                        ['label' => 'Green Hydrogen Initiative'],
                        ['label' => 'Renewable Startup'],
                    ],
                    '51. Retail' => [
                        ['label' => 'Retail Brand of the Year'],
                        ['label' => 'Omni-Channel Excellence'],
                        ['label' => 'Customer Experience'],
                        ['label' => 'Retail Expansion Leader'],
                        ['label' => 'Digital Retail Innovation'],
                    ],
                    '52. Robotics' => [
                        ['label' => 'Robotics Innovation'],
                        ['label' => 'Industrial Automation'],
                        ['label' => 'AI Robotics Excellence'],
                        ['label' => 'Smart Manufacturing Robotics'],
                        ['label' => 'Robotics Startup'],
                    ],
                    '53. Retail' => [
                        ['label' => 'Retail Brand of the Year'],
                        ['label' => 'Omni-Channel Retail Excellence'],
                        ['label' => 'Store Experience Innovation'],
                        ['label' => 'Retail Expansion Leader'],
                        ['label' => 'Customer Experience in Retail'],
                    ],
                    '54. Renewable Energy' => [
                        ['label' => 'Solar Energy Excellence'],
                        ['label' => 'Wind Energy Innovation'],
                        ['label' => 'Hybrid Energy Solutions'],
                        ['label' => 'Energy Storage Innovation'],
                        ['label' => 'Renewable Startup of the Year'],
                    ],
                    '55. Real Estate' => [
                        ['label' => 'Residential Project Excellence'],
                        ['label' => 'Commercial Project of the Year'],
                        ['label' => 'Smart Infrastructure Development'],
                        ['label' => 'Sustainable Real Estate'],
                        ['label' => 'Affordable Housing Leadership'],
                    ],
                    '56. Research & Development (R&D)' => [
                        ['label' => 'Innovation Excellence'],
                        ['label' => 'Product Development Breakthrough'],
                        ['label' => 'Industrial R&D Leadership'],
                        ['label' => 'Deep Tech Innovation'],
                        ['label' => 'Patent & IP Excellence'],
                    ],
                    '57. Robotics & Automation' => [
                        ['label' => 'Industrial Automation Excellence'],
                        ['label' => 'Robotics Innovation Award'],
                        ['label' => 'AI-driven Automation'],
                        ['label' => 'Smart Factory Implementation'],
                        ['label' => 'Robotics Startup of the Year'],
                    ],
                    '58. Steel & Metals' => [
                        ['label' => 'Metal Manufacturing Excellence'],
                        ['label' => 'Export Excellence – Metals'],
                        ['label' => 'Sustainable Steel Production'],
                        ['label' => 'Innovation in Metal Processing'],
                        ['label' => 'Industry Leadership Award'],
                    ],
                    '59. Startups' => [
                        ['label' => 'Startup of the Year'],
                        ['label' => 'Disruptive Innovation Startup'],
                        ['label' => 'Tech Startup Excellence'],
                        ['label' => 'Social Impact Startup'],
                        ['label' => 'Fastest Growing Startup'],
                    ],
                    '60. Telecom' => [
                        ['label' => 'Telecom Innovation Award'],
                        ['label' => '5G Implementation Excellence'],
                        ['label' => 'Digital Connectivity Leader'],
                        ['label' => 'Rural Connectivity Impact'],
                        ['label' => 'Infrastructure Excellence'],
                    ],
                    '61. Textiles & Apparel' => [
                        ['label' => 'Textile Innovation Award'],
                        ['label' => 'Sustainable Fashion Brand'],
                        ['label' => 'Export Excellence – Apparel'],
                        ['label' => 'Technical Textiles Leadership'],
                        ['label' => 'Manufacturing Excellence'],
                    ],
                    '62. Travel & Tourism' => [
                        ['label' => 'Destination of the Year'],
                        ['label' => 'Tour Operator Excellence'],
                        ['label' => 'Eco-Tourism Leadership'],
                        ['label' => 'Luxury Travel Experience'],
                        ['label' => 'Hospitality Excellence'],
                    ],
                    '63. Warehousing & Logistics' => [
                        ['label' => 'Logistics Excellence Award'],
                        ['label' => 'Supply Chain Innovation'],
                        ['label' => 'Smart Warehouse Automation'],
                        ['label' => 'Cold Chain Excellence'],
                        ['label' => 'Green Logistics Leader'],
                    ],
                    '64. Water Conservation' => [
                        ['label' => 'Water Management Excellence'],
                        ['label' => 'Wastewater Recycling Innovation'],
                        ['label' => 'Rainwater Harvesting Leadership'],
                        ['label' => 'Smart Water Technology'],
                        ['label' => 'Community Water Impact'],
                    ],
                    '65. Waste Management' => [
                        ['label' => 'Waste Recycling Excellence'],
                        ['label' => 'Circular Economy Leadership'],
                        ['label' => 'Plastic Waste Management'],
                        ['label' => 'Industrial Waste Innovation'],
                        ['label' => 'Waste-to-Energy Leader'],
                    ],
                    '66. Packaging Industry' => [
                        ['label' => 'Flexible Packaging Excellence'],
                        ['label' => 'Rigid Packaging Innovation'],
                        ['label' => 'Sustainable Packaging Leader'],
                        ['label' => 'Printing & Converting Excellence'],
                        ['label' => 'Packaging Design Innovation'],
                    ],
                    '67. Printing & Converting' => [
                        ['label' => 'Printing Technology Innovation'],
                        ['label' => 'Label & Packaging Printing Excellence'],
                        ['label' => 'Digital Printing Leadership'],
                        ['label' => 'Sustainable Printing Solutions'],
                        ['label' => 'Converting Excellence'],
                    ],
                    '68. Specialty Chemicals' => [
                        ['label' => 'Chemical Innovation Award'],
                        ['label' => 'Green Chemistry Leadership'],
                        ['label' => 'Process Excellence'],
                        ['label' => 'Export Excellence'],
                        ['label' => 'R&D in Chemicals'],
                    ],
                    '69. Pharmaceuticals' => [
                        ['label' => 'Pharma Innovation Award'],
                        ['label' => 'API Manufacturing Excellence'],
                        ['label' => 'Healthcare Impact Award'],
                        ['label' => 'Export Excellence – Pharma'],
                        ['label' => 'R&D Leadership'],
                    ],
                    '70. Healthcare & Hospitals' => [
                        ['label' => 'Hospital of the Year'],
                        ['label' => 'Patient Care Excellence'],
                        ['label' => 'Medical Innovation Award'],
                        ['label' => 'Healthcare Startup'],
                        ['label' => 'Rural Healthcare Impact'],
                    ],
                    '71. Food Processing & FMCG' => [
                        ['label' => 'FMCG Brand of the Year'],
                        ['label' => 'Food Innovation Award'],
                        ['label' => 'Packaging Excellence (FMCG)'],
                        ['label' => 'Supply Chain Excellence'],
                        ['label' => 'Export Excellence'],
                    ],
                    '72. Hospitality (Hotels & Resorts)' => [
                        ['label' => 'Hotel of the Year'],
                        ['label' => 'Luxury Hospitality Award'],
                        ['label' => 'Boutique Hotel Excellence'],
                        ['label' => 'Guest Experience Innovation'],
                        ['label' => 'Sustainable Hospitality'],
                    ],
                    '73. Media & Advertising' => [
                        ['label' => 'Creative Campaign of the Year'],
                        ['label' => 'Digital Marketing Excellence'],
                        ['label' => 'Brand Strategy Innovation'],
                        ['label' => 'Media Agency of the Year'],
                        ['label' => 'Influencer Marketing Excellence'],
                    ],
                    '74. IT & Software' => [
                        ['label' => 'Software Innovation Award'],
                        ['label' => 'SaaS Company of the Year'],
                        ['label' => 'IT Services Excellence'],
                        ['label' => 'Cloud Transformation Leader'],
                        ['label' => 'AI-driven IT Solutions'],
                    ],
                    '75. Legal & Compliance' => [
                        ['label' => 'Legal Excellence Award'],
                        ['label' => 'Corporate Law Firm of the Year'],
                        ['label' => 'Compliance Leadership'],
                        ['label' => 'ESG Compliance Excellence'],
                        ['label' => 'Risk Advisory Excellence'],
                    ],
                    '76. Human Resources (HR)' => [
                        ['label' => 'HR Innovation Award'],
                        ['label' => 'Talent Management Excellence'],
                        ['label' => 'Employee Engagement Leader'],
                        ['label' => 'Diversity & Inclusion Champion'],
                        ['label' => 'HR Tech Innovation'],
                    ],
                    '77. Import & Export' => [
                        ['label' => 'Export Excellence Award'],
                        ['label' => 'Global Trade Leader'],
                        ['label' => 'Import Substitution Champion'],
                        ['label' => 'Supply Chain Excellence'],
                        ['label' => 'International Expansion Award'],
                    ],
                    '78. NGOs & Social Impact' => [
                        ['label' => 'NGO of the Year'],
                        ['label' => 'Social Innovation Award'],
                        ['label' => 'Community Impact Leadership'],
                        ['label' => 'Women Empowerment Initiative'],
                        ['label' => 'Rural Development Excellence'],
                    ],
                    '79. Award Benefits (Positioning Categories)' => [
                        ['label' => 'Global Recognition Award'],
                        ['label' => 'Industry Leadership Recognition'],
                        ['label' => 'Innovation Excellence Recognition'],
                        ['label' => 'Sustainability Leadership Recognition'],
                        ['label' => 'Brand Visibility Excellence'],
                        ['label' => 'Export Recognition Award'],
                        ['label' => 'ESG Impact Recognition'],
                    ],
                    '80. Recycling Sector – Exclusivity Award' => [
                        ['label' => 'Recycling Company of the Year (Exclusive)'],
                        ['label' => 'Plastic Recycling Leader (Exclusive)'],
                        ['label' => 'Circular Economy Champion'],
                        ['label' => 'Global Recycling Innovator'],
                        ['label' => 'Waste-to-Resource Pioneer'],
                    ],
                    '81. Waste Management – Exclusivity Award' => [
                        ['label' => 'Waste Management Company of the Year (Exclusive)'],
                        ['label' => 'Integrated Waste Solutions Leader'],
                        ['label' => 'Smart Waste Technology Leader'],
                        ['label' => 'Municipal Waste Excellence'],
                        ['label' => 'Industrial Waste Leader'],
                    ],
                    '82. Solar Energy – Exclusivity Award' => [
                        ['label' => 'Solar Company of the Year (Exclusive)'],
                        ['label' => 'Solar EPC Leader'],
                        ['label' => 'Solar Innovation Excellence'],
                        ['label' => 'Utility-Scale Solar Leader'],
                        ['label' => 'Rooftop Solar Champion'],
                    ],
                    '83. Automobile Industry – Exclusivity Award' => [
                        ['label' => 'Automobile Company of the Year (Exclusive)'],
                        ['label' => 'Auto Innovation Leader'],
                        ['label' => 'EV Transition Leader'],
                        ['label' => 'Global Automotive Excellence'],
                        ['label' => 'Manufacturing Excellence – Auto'],
                    ],
                    '84. Electric Mobility – Exclusivity Award' => [
                        ['label' => 'EV Company of the Year (Exclusive)'],
                        ['label' => 'EV Innovation Leader'],
                        ['label' => 'Charging Infrastructure Leader'],
                        ['label' => 'Battery Technology Leader'],
                        ['label' => 'Clean Mobility Champion'],
                    ],
                    '85. Battery Recycling – Exclusivity Award' => [
                        ['label' => 'Battery Recycling Company of the Year (Exclusive)'],
                        ['label' => 'Lithium Battery Recycling Leader'],
                        ['label' => 'Circular Battery Innovation'],
                        ['label' => 'Energy Storage Sustainability Leader'],
                        ['label' => 'Hazardous Waste Recycling'],
                    ],
                ],
                'order' => 3,
            ],
        ];

        // Clear existing fields to avoid duplicates
        $form->fields()->delete();

        foreach ($fields as $fieldData) {
            $form->fields()->create($fieldData);
        }
    }
}
