<?php

return [
    'sectors' => [
        [
            'title' => 'Chemicals & Petrochemicals',
            'description' => 'The backbone of modern manufacturing transforming raw materials into value-added products for global industries.',
            'thumbnail' => 'images/sectors/chemicals-petrochemicals-industry.jpg',
            'slug' => 'chemicals-petrochemicals-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Plastic Industry',
            'description' => 'The plastic industry is a global industry that produces a wide range of plastic products.',
            'thumbnail' => 'images/sectors/plastic-industry.png',
            'slug' => 'plastic-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Plastic Machinery',
            'description' => 'Plastic machinery is a global industry that produces a wide range of plastic products.',
            'thumbnail' => 'images/sectors/plastic-machinery.jpg',
            'slug' => 'plastic-machinery',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Plastic Recycling',
            'description' => 'Processing waste plastics into reusable raw materials — reducing landfills and promoting circular economy.',
            'thumbnail' => 'images/sectors/plastic-recycling.jpeg',
            'slug' => 'plastic-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'E-Waste Recycling',
            'description' => 'Collection, dismantling, and recovery of valuable materials from discarded electronics and equipment.',
            'thumbnail' => 'images/sectors/e-waste-recycling.jpeg',
            'slug' => 'e-waste-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Non-Ferrous & Scrap Recycling',
            'description' => 'Collection, processing, and reuse of non-iron metals and industrial scrap into secondary raw materials.',
            'thumbnail' => 'images/sectors/non-ferrous-scrap-recycling.jpeg',
            'slug' => 'non-ferrous-scrap-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Lithium Battery Recycling',
            'description' => 'Lithium battery recycling is the process of recycling lithium batteries.',
            'thumbnail' => 'images/sectors/lithium-battery-recycling.webp',
            'slug' => 'lithium-battery-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Solar Recycling',
            'description' => 'Solar recycling is the process of recycling solar panels.',
            'thumbnail' => 'images/sectors/solar-recycling.jpeg',
            'slug' => 'solar-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Chemical Recycling',
            'description' => 'Chemical recycling is the process of recycling chemical products.',
            'thumbnail' => 'images/sectors/chemical-recycling.jpg',
            'slug' => 'chemical-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Packaging Machinery',
            'description' => 'Packaging machinery is a global industry that produces a wide range of plastic products.',
            'thumbnail' => 'images/sectors/packaging-machinery.jpg',
            'slug' => 'packaging-machinery',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Other Types of Packaging',
            'description' => 'Other types of packaging is a global industry that produces a wide range of plastic products.',
            'thumbnail' => 'images/sectors/other-types-of-packaging.webp',
            'slug' => 'other-types-of-packaging',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Flexible & Rigid Packaging',
            'description' => 'Flexible & rigid packaging is a global industry that produces a wide range of plastic products.',
            'thumbnail' => 'images/sectors/flexible-rigid-packaging.jpeg',
            'slug' => 'flexible-rigid-packaging',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Manufacturing',
            'description' => 'Manufacturing is the production of goods on a large scale.',
            'thumbnail' => 'images/sectors/manufacturing.jpg',
            'slug' => 'manufacturing',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Sustainability Leadership',
            'description' => 'Strategic vision integrating environmental, social, and economic responsibility into core business operations.',
            'thumbnail' => 'images/sectors/sustainability-leadership.jpg',
            'slug' => 'sustainability-leadership',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Circular Economy',
            'description' => 'Economic model focused on minimizing waste, maximizing resource efficiency, and regenerating materials.',
            'thumbnail' => 'images/sectors/circular-economy.jpg',
            'slug' => 'circular-economy',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Renewable Energy',
            'description' => 'Renewable energy is energy that is collected from renewable resources, which are naturally replenished on a human timescale, such as sunlight, wind, rain, tides, waves, and geothermal heat.',
            'thumbnail' => 'images/sectors/renewable-energy.png',
            'slug' => 'renewable-energy',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Biogas',
            'description' => 'Renewable energy from anaerobic digestion of organic waste for power, heating, and clean fuel production.',
            'thumbnail' => 'images/sectors/biogas-industry.webp',
            'slug' => 'biogas-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Biofuel / Bio Energy',
            'description' => 'Renewable energy from biological and organic materials for power, transport, and industrial applications.',
            'thumbnail' => 'images/sectors/biofuel.jpg',
            'slug' => 'biofuel-bioenergy',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Hydrogen',
            'description' => 'Clean energy carrier for power generation, industrial processes, mobility, and global decarbonization.',
            'thumbnail' => 'images/sectors/hydrogen-industry.jpg',
            'slug' => 'hydrogen-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Start-Up Ecosystem',
            'description' => 'Innovation-driven entrepreneurial ventures with scalable business models and high growth potential.',
            'thumbnail' => 'images/sectors/start-up-ecosystem.jpg',
            'slug' => 'start-up-ecosystem',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Corporate Social Responsibility',
            'description' => 'Ethical business commitment contributing to society, environment, and economic development.',
            'thumbnail' => 'images/sectors/csr.jpg',
            'slug' => 'csr',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Electric Mobility',
            'description' => 'Electric mobility is the use of electric vehicles for transportation.',
            'thumbnail' => 'images/sectors/electric-mobility.jpg',
            'slug' => 'electric-mobility',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Water Conservation',
            'description' => 'Efficient management, preservation, and sustainable use of water resources for long-term sustainability.',
            'thumbnail' => 'images/sectors/water-conservation.jpg',
            'slug' => 'water-conservation',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Waste Management',
            'description' => 'Systematic collection, processing, recycling, and disposal of waste for environmental sustainability.',
            'thumbnail' => 'images/sectors/waste-management.jpg',
            'slug' => 'waste-management',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Tyre & Rubber Recycling',
            'description' => 'Collection, processing, and repurposing of used tyres and rubber waste into reusable materials and energy.',
            'thumbnail' => 'images/sectors/tyre-rubber-recycling.jpg',
            'slug' => 'tyre-rubber-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Glass Recycling',
            'description' => 'Collecting, sorting, and re-melting waste glass into reusable raw material — 100% infinitely recyclable.',
            'thumbnail' => 'images/sectors/glass-recycling.jpg',
            'slug' => 'glass-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'ESG Industry',
            'description' => 'Environmental, Social, and Governance (ESG) is a strategic framework evaluating business sustainability and ethics.',
            'thumbnail' => 'images/sectors/esg.jpeg',
            'slug' => 'esg-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'EPR Industry',
            'description' => 'Extended Producer Responsibility (EPR) holds producers responsible for the collection and recycling of their products.',
            'thumbnail' => 'images/sectors/waste-management.jpg',
            'slug' => 'epr-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Food & Beverages',
            'description' => 'Global industry covering processing, manufacturing, packaging, and distribution of edible products and drinks.',
            'thumbnail' => 'images/sectors/rice.png',
            'slug' => 'food-beverages-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Home Furnishing',
            'description' => 'Manufacturing and design of interior lifestyle products including textiles, décor, and luxury furnishings.',
            'thumbnail' => 'images/sectors/home.jpeg',
            'slug' => 'home-furnishing-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Handicraft',
            'description' => 'Preserving cultural heritage through handmade artistic products including décor, wooden crafts, and traditional artwork.',
            'thumbnail' => 'images/sectors/handicraft.webp',
            'slug' => 'handicraft-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Garments',
            'description' => 'Global fashion and apparel manufacturing covering ready-made clothing for men, women, and children.',
            'thumbnail' => 'images/sectors/garments.webp',
            'slug' => 'garments-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Textile',
            'description' => 'Global manufacturing backbone covering fibers, yarns, fabrics, and technical textiles for diverse industrial applications.',
            'thumbnail' => 'images/sectors/textile.png',
            'slug' => 'textile-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Leather',
            'description' => 'Premium manufacturing of footwear, bags, and luxury accessories, blending durability with timeless style.',
            'thumbnail' => 'images/sectors/leather.webp',
            'slug' => 'leather-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Jute',
            'description' => 'Global leader in the "Golden Fiber" industry, providing sustainable and eco-friendly packaging and textile solutions.',
            'thumbnail' => 'images/sectors/jute-industry.jpg',
            'slug' => 'jute-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Food Waste Recycling',
            'description' => 'Transforming discarded organic waste into compost, biogas, and bio-fertilizers for a sustainable planet.',
            'thumbnail' => 'images/sectors/food-waste-recycling.jpg',
            'slug' => 'food-waste-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Pharmaceuticals Industry',
            'description' => 'Research-driven sector dedicated to the discovery, development, and manufacturing of life-saving medicines and vaccines.',
            'thumbnail' => 'images/sectors/pharma-hero.png',
            'slug' => 'pharmaceuticals-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Healthcare Industry',
            'description' => 'Vital infrastructure covering medical services, hospitals, diagnostics, and biotechnology for global public health.',
            'thumbnail' => 'images/sectors/healthcare-hero.png',
            'slug' => 'healthcare-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Information Technology',
            'description' => 'Digital backbone powering global business through software development, AI, cloud computing, and cybersecurity.',
            'thumbnail' => 'images/sectors/it-hero.png',
            'slug' => 'it-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Flexible Packaging Inks',
            'description' => 'Specialized inks for vibrant graphics on plastic films, laminates, and pouches in food, pharma, and FMCG sectors.',
            'thumbnail' => 'images/sectors/packaging-inks-hero.png',
            'slug' => 'flexible-packaging-inks',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Flexible Packaging Adhesives',
            'description' => 'Specialized bonding materials for multilayer packaging structures used in food, pharma, and industrial sectors.',
            'thumbnail' => 'images/sectors/packaging-adhesives-hero.png',
            'slug' => 'flexible-packaging-adhesives',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Oil & Gas Industry',
            'description' => 'Critical energy sector powering global transportation and industrial production through hydrocarbons and LNG.',
            'thumbnail' => 'images/sectors/oil-gas-hero.png',
            'slug' => 'oil-gas-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Aluminium Recycling',
            'description' => 'Sustainable processing and reuse of aluminium scrap, saving 95% energy compared to primary production.',
            'thumbnail' => 'images/sectors/non-ferrous-scrap-recycling.jpeg',
            'slug' => 'aluminium-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Wood Recycling',
            'description' => 'Sustainable recovery of wood waste into particle boards, biomass fuel, and eco-friendly furniture.',
            'thumbnail' => 'images/sectors/wood-recycling-hero.png',
            'slug' => 'wood-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Cigarette Butts Recycling',
            'description' => 'Innovative recovery of cellulose acetate from cigarette filters to produce industrial stuffing and plastic alternatives.',
            'thumbnail' => 'images/sectors/circular-economy.jpg',
            'slug' => 'cigarette-butts-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Automobile Recycling',
            'description' => 'The systematic process of dismantling, recovering, and reprocessing materials from end-of-life vehicles (ELVs).',
            'thumbnail' => 'images/sectors/automobile-recycling.jpg',
            'slug' => 'automobile-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Paper Recycling',
            'description' => 'The process of converting waste paper and cardboard into reusable raw materials for manufacturing new paper products.',
            'thumbnail' => 'images/sectors/paper-recycling.jpg',
            'slug' => 'paper-recycling',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Decarbonization / Carbon Net Zero',
            'description' => 'The process of reducing or eliminating CO2 and greenhouse gas emissions from industrial and societal activities.',
            'thumbnail' => 'images/sectors/decarbonization.jpg',
            'slug' => 'decarbonization',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Agro & Food Processing',
            'description' => 'The transformation of agricultural raw materials into value-added food, beverage, and industrial products.',
            'thumbnail' => 'images/sectors/agro-food-processing.jpg',
            'slug' => 'agro-food-processing',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Cyber Security',
            'description' => 'Safeguarding organizations, governments, and individuals against cyber threats, data breaches, and digital fraud.',
            'thumbnail' => 'images/sectors/cyber-security.jpg',
            'slug' => 'cyber-security',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'FMCG Industry',
            'description' => 'Fast Moving Consumer Goods (FMCG) represent products that are sold quickly at relatively low cost and are consumed on a regular basis.',
            'thumbnail' => 'images/sectors/fmcg-industry.jpg',
            'slug' => 'fmcg-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Import & Export',
            'description' => 'Driving global trade, enabling businesses to exchange goods and services across international borders.',
            'thumbnail' => 'images/sectors/import-export.jpg',
            'slug' => 'import-export',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Tourism Industry',
            'description' => 'Connecting cultures, economies, and experiences across the globe through travel and hospitality.',
            'thumbnail' => 'images/sectors/tourism-industry.jpg',
            'slug' => 'tourism-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Electronics Industry',
            'description' => 'Empowering the modern world through innovative smart technology, semiconductors, and electronic devices.',
            'thumbnail' => 'images/sectors/electronics-industry.jpg',
            'slug' => 'electronics-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'AI for Industry',
            'description' => 'Artificial Intelligence is no longer sector-specific—it is a horizontal capability layer transforming every major industry.',
            'thumbnail' => 'images/sectors/ai-for-industry.jpg',
            'slug' => 'ai-for-industry',
            'route' => 'sectors.show',
        ],
        [
            'title' => 'Commerce & Industry',
            'description' => 'A strategic bridge between businesses, government, and global markets empowering trade and industrial growth.',
            'thumbnail' => 'images/sectors/commerce-industry-hero.png',
            'slug' => 'commerce-and-industry',
            'route' => 'sectors.show',
        ],
    ]
];
