@extends('layouts.website')
@section('title', 'Welcome to World Grexpo Foundation')
@section('content')
    @include('website.home.partials.hero')
    @include('website.home.partials.about')
    @include('website.home.partials.events')
    @include('website.home.partials.excellence')
    @include('website.home.partials.services')
    @include('website.home.partials.awards')
    @include('website.home.partials.sectors')
    @include('website.home.partials.gallery_preview')
    @include('website.home.partials.blog_preview')
    @include('website.home.partials.faqs')
    @include('website.home.partials.popup')
@endsection
